### ISSUE TITLE
♿ アクセシビリティ改善

### ISSUE THREAD

**Issue by masahide0902** [masahide0902/my-first-github-project#8]
## 📋 概要
Webアクセシビリティガイドライン（WCAG 2.1）に準拠し、より多くのユーザーが利用しやすいサイトに改善します。

## 🎯 目標
- キーボードナビゲーション完全対応
- スクリーンリーダー対応
- 高コントラストモード対応
- フォーカス表示の改善

### キーボードナビゲーション
- [ ] Tab順序の最適化
- [ ] Enterキーでのボタン操作
- [ ] Escapeキーでのモーダル閉じる
- [ ] 矢印キーでの要素移動

### スクリーンリーダー対応
- [ ] 適切なaria-label属性の追加
- [ ] role属性の設定
- [ ] aria-describedby属性の実装
- [ ] 見出し構造の最適化

### 視覚的改善
- [ ] フォーカスリングの視認性向上
- [ ] 色だけに依存しない情報伝達
- [ ] 十分なコントラスト比の確保
- [ ] テキストサイズの調整可能性

### HTML改善
- [ ] セマンティックHTMLの徹底
- [ ] alt属性の適切な設定
- [ ] lang属性の設定
- [ ] skip linkの追加

### WCAG 2.1 レベルAA準拠
- [ ] 1.1.1 非テキストコンテンツ
- [ ] 1.3.1 情報と関係性
- [ ] 1.4.3 コントラスト（最低限）
- [ ] 2.1.1 キーボード
- [ ] 2.1.2 キーボードトラップなし
- [ ] 2.4.1 ブロックスキップ
- [ ] 2.4.2 ページタイトル
- [ ] 2.4.3 フォーカス順序
- [ ] 3.1.1 ページの言語
- [ ] 3.2.1 フォーカス時
- [ ] 4.1.1 構文解析
- [ ] 4.1.2 名前、役割、値

### CSS
```css
/* フォーカス表示の改善 */
:focus-visible {
    outline: 2px solid #4a9eff;
    outline-offset: 2px;
}

/* 高コントラストモード */
@media (prefers-contrast: high) {
    /* 高コントラスト用スタイル */
}
```

### JavaScript
```javascript
// キーボードナビゲーション
document.addEventListener('keydown', handleKeyboardNavigation);

// スクリーンリーダー用の動的コンテンツ通知
function announceToScreenReader(message) {
    const announcement = document.createElement('div');
    announcement.setAttribute('aria-live', 'polite');
    announcement.textContent = message;
    document.body.appendChild(announcement);
}
```

## ✅ 完了条件
- [ ] 全ての機能がキーボードのみで操作可能
- [ ] スクリーンリーダーで適切に読み上げられる
- [ ] axe-coreでのアクセシビリティテストをパス
- [ ] Lighthouseアクセシビリティスコア90以上
- [ ] 実際の支援技術でのテスト完了

## 🔗 関連
- SITE_IMPROVEMENT_PLAN.md の短期改善計画
- 優先度: 🔥 高
- 参考: WCAG 2.1 ガイドライン
